### ISSUE TITLE
Sometimes display arrows on self

### ISSUE THREAD

**Issue by MC-luoluo** [Polyfrost/PolyHitbox#2]
Screenshots only use this mod with forge, they will not be displayed when this mod is disabled
![2024-06-25_06 06 07](https://github.com/Polyfrost/PolyHitbox/assets/113677351/a738d4c4-3805-4c3a-984d-1abb0ed5fc0f)
I couldn't reproduce this using dispenser in single player game, but it was easy to reproduce in the Hypixel pit.

**Comment by Wyvest** [comment]
Can you go to discord.gg/polyfrost and make a ticket? thanks

**Comment by Wyvest** [comment]
Fixed in latest release
